source 'https://rubygems.org'

gem 'jekyll-assets'
gem 'jekyll-contentblocks'

gem 'coffee-script'
gem 'gemoji'
gem 'jekyll-asciinema'
gem 'jekyll-mermaid'
gem 'jemoji'
gem 'pygments.rb'
gem 'redcarpet'
gem 'sass'
gem 'uglifier'
gem 'yui-compressor'
