title:            keff.me
description:      a coding blog
url:              http://keff.me
permalink: /:year/:month/:day/:title/
relative_permalinks: false

# Owner/author information
owner:
  name:           Kevin Chen
  email:          kvchen@berkeley.edu
social:
  github:         https://github.com/kvchen
  facebook:       https://www.facebook.com/nuclearsalad
  google_plus:    https://plus.google.com/+KevinChen0/posts
  linkedin:       http://www.linkedin.com/pub/kevin-chen/70/b70/836


# Analytics and webmaster tools stuff goes here
google_analytics: UA-42434200-1

# Links to include in top navigation
links:
  - title: Home
    url: /
#  - title: Blog
#  - title: Projects
#    url: /projects/
  - title: Resources
    url: /resources/

# Logistics
gems: []
include: [".htaccess"]
exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

assets:
  js_compressor: uglify
  css_compressor: yui

timezone:    America/Los_Angeles
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class


