title: keff
description: breaking and building
url: http://localhost:4000
permalink: /:year/:month/:day/:title/
relative_permalinks: false
encoding: utf-8

# Owner/author information

author:
  fullname: Kevin Chen
  facebook: keffcat
  github: kvchen
  keybase: kevinchen

google_analytics: UA-42434200-1


# Logistics

include: [".htaccess"]
exclude: ["Rakefile", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

assets:
  js_compressor: uglify
  css_compressor: yui

timezone: America/Los_Angeles
future: true

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
